[TOC]

首先祝大家儿童节快乐~

任务还要继续，今天的主题是**错误和异常**

## 错误和异常

### 语法错误

SyntaxError



### 异常

```python
>>> 10 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

- 最后一行显示了错误的类型
- 错误信息的前一部分以堆栈回溯的形式显示发生异常时的上下文



### 处理异常

`try-except-finally` 语句

工作原理：

1. 执行try-except之间的语句
2. 没有发生异常直接掉过except语句
3. 发生异常，跳过子句剩下的部分。如果异常类型和except后的类型匹配，则执行except之后的语句，然后继续执行try之后的代码
4. 发生的异常和except之后的类型不匹配，则传递到外部的try语句中；如果没有找到处理程序，则认为这是一个**未处理异常**，执行停止。
5. finally语句在发生异常时也会执行，通常用于执行一些清理工作（如释放资源）

一个try语句可以有多个except子句

```python
try:
    pass
except RuntimeError:
    pass
except TypeError:
	pass
except NameError:
    pass
```

一个except语句可以将多个异常放到一起

```python
try:
    pass
except (RuntimeError, TypeError, NameError):
    pass
```

except子句可以省略异常名，用于通配，但请谨慎使用，以免掩盖真正的错误信息



### 抛出异常

`raise` 语句引发指定异常

```python
# 抛出异常格式
raise 异常（Exception Instance / Exception Class）

raise ValueError # 调用无参构造函数，和下面的效果一样
raise ValueError()
```



### 用户自定义异常类

略